eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
server:
  port: 8762
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
